### ISSUE TITLE
can not build it

### ISSUE THREAD

**Issue by tsgan** [segment-sources/mysql#5]
tsgan@bsd:~/go/src/github.com/segment-sources/mysql % go build
# github.com/segmentio/objects-go

../../segmentio/objects-go/client.go:97: cannot use req.Properties (type map[string]interface {}) as type *tableize.Input in argument to tableize.Tableize
../../segmentio/objects-go/client.go:111: cannot use req.Properties (type map[string]interface {}) as type *tableize.Input in argument to tableize.Tableize
tsgan@bsd:~/go/src/github.com/segment-sources/mysql % go version
go version go1.6.2 freebsd/amd64

**Comment by tejasmanohar** [comment]
Tableize was updated, and we don't vendor / pin versions. Let's do that.

**Comment by tejasmanohar** [comment]
@vinceprignano @liquidy

**Comment by liquidy** [comment]
@tsgan just fixed the call. Let me know if you're still having issues.

@tejasmanohar also added Godeps vendoring so people can more easily get around this issue in the future.
